config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: %i[index new edit create update]

  resources :financing_sources do
    get 'export', to: 'financing_sources#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'financing_sources#import', as: :import, on: :collection
    post 'import', to: 'financing_sources#import_upload', as: :import_upload, on: :collection
  end

  resources :project_categories

  resources :expenditure_articles do
    get 'export', to: 'expenditure_articles#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'expenditure_articles#import', as: :import, on: :collection
    post 'import', to: 'expenditure_articles#import_upload', as: :import_upload, on: :collection
  end

  resources :payment_types do
    get 'export', to: 'payment_types#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'payment_types#import', as: :import, on: :collection
    post 'import', to: 'payment_types#import_upload', as: :import_upload, on: :collection
  end

  resources :expenditures, only: %i[index new edit create update] do
    get 'duplicate', to: 'expenditures#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'expenditures#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'expenditures#import', as: :import
      post 'import', to: 'expenditures#import_upload', as: :import_upload
      get 'find_matching_invoices', to: 'expenditures#find_matching_invoices',
                                    as: :find_matching_invoices,
                                    defaults: { format: :json }
      get 'find_matching_beneficiaries', to: 'expenditures#find_matching_beneficiaries',
                                         as: :find_matching_beneficiaries,
                                         defaults: { format: :json }
    end
  end

  resources :commitments, only: %i[index new edit create update] do
    get 'duplicate', to: 'commitments#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'commitments#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'commitments#import', as: :import
      post 'import', to: 'commitments#import_upload', as: :import_upload
    end
  end

  resources :settings, only: %i[index] do
    post 'update', to: 'settings#update', as: :update, on: :collection
  end

  get :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report', as: :generate_pfc_activity_report
  post :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report'
  get :pfc_activity_report, to: 'reports#pfc_activity_report', as: :download_pfc_activity_report, format: 'xlsx'

  resources :audit_events, only: [:index]
end

app/models/expenditure_article.rb
# frozen_string_literal: true

class ExpenditureArticle < ApplicationRecord
  validates :code, :name, presence: true, uniqueness: true

  normalizes :code, :name, with: ->(str) { str.strip }

  has_many :expenditures, dependent: :restrict_with_error
  has_many :commitments, dependent: :restrict_with_error
end

app/controllers/expenditure_articles_controller.rb
# frozen_string_literal: true

class ExpenditureArticlesController < ApplicationController
  before_action -> { require_permission 'ExpenditureArticle.View' }, only: %i[index export_download]
  before_action -> { require_permission 'ExpenditureArticle.Create' }, only: %i[new create import import_upload]
  before_action -> { require_permission 'ExpenditureArticle.Edit' }, only: %i[edit update]
  before_action -> { require_permission 'ExpenditureArticle.Delete' }, only: %i[destroy]

  def index
    @expenditure_articles = ExpenditureArticle.order(code: :asc)
  end

  def new
    @expenditure_article = ExpenditureArticle.new
  end

  def edit
    expenditure_article_id = params.require(:id)
    @expenditure_article = ExpenditureArticle.find(expenditure_article_id)
  end

  def create
    @expenditure_article = ExpenditureArticle.new expenditure_article_params

    successfully_saved = false
    ExpenditureArticle.transaction do
      successfully_saved = @expenditure_article.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :insert,
          target_table: :expenditure_articles,
          target_object_id: @expenditure_article.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost salvat cu succes articolul de cheltuială cu codul #{@expenditure_article.code}"
      redirect_to expenditure_articles_path
    else
      flash[:alert] = 'Nu s-a putut salva noul articol de cheltuială. Verificați erorile și încercați din nou.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    expenditure_article_id = params.require(:id)
    @expenditure_article = ExpenditureArticle.find(expenditure_article_id)

    @expenditure_article.assign_attributes expenditure_article_params

    successfully_saved = false
    ExpenditureArticle.transaction do
      successfully_saved = @expenditure_article.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :update,
          target_table: :expenditure_articles,
          target_object_id: @expenditure_article.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost actualizat cu succes articolul de cheltuială cu codul #{@expenditure_article.code}"
      redirect_to expenditure_articles_path
    else
      flash[:alert] =
        'Nu s-au putut salva modificările la articolul de cheltuială. Verificați erorile și încercați din nou.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    expenditure_article_id = params.require(:id)
    @expenditure_article = ExpenditureArticle.find(expenditure_article_id)

    successfully_deleted = false
    ExpenditureArticle.transaction do
      successfully_deleted = @expenditure_article.destroy

      if successfully_deleted
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :delete,
          target_table: :expenditure_articles,
          target_object_id: @expenditure_article.id
        )
      end
    end

    if successfully_deleted
      flash[:notice] = "A fost șters cu succes articolul de cheltuială cu codul #{@expenditure_article.code}"
    else
      flash[:alert] =
        "Nu s-a putut șterge articolul de cheltuială: #{@expenditure_article.errors.full_messages.join(', ')}."
    end

    redirect_to expenditure_articles_path
  end

  def export_download
    @expenditure_articles = ExpenditureArticle.order(name: :asc)
    date = Time.current.strftime('%Y-%m-%d')
    render xlsx: 'export', template: 'expenditure_articles/export',
           disposition: 'attachment', filename: "Export articole de cheltuială #{date}.xlsx"
  end

  def import; end

  def import_upload
    uploaded_file = params.require(:file)
    spreadsheet = Roo::Spreadsheet.open(uploaded_file)
    sheet = spreadsheet.sheet(0)

    total_count = 0
    ExpenditureArticle.transaction do
      (2..sheet.last_row).each do |row_index|
        row = sheet.row row_index

        code = row[0].strip

        expenditure_article = ExpenditureArticle.find_or_initialize_by(code:)

        expenditure_article.name = row[1].strip
        expenditure_article.expenditure_category_code = (row[2].presence || '').strip
        expenditure_article.commitment_category_code = (row[3].presence || '').strip

        unless expenditure_article.save
          raise ImportError.new(row_index, expenditure_article.errors.full_messages.join(', '))
        end

        total_count += 1
      end
    end

    flash[:notice] = "S-au importat/actualizat cu succes #{total_count} articole de cheltuială!"
    redirect_to expenditure_articles_path
  rescue ImportError => e
    flash.now[:alert] = e.to_s
    render :import
  end

  private

  def expenditure_article_params
    params.expect(expenditure_article: %i[code expenditure_category_code commitment_category_code name])
  end
end

app/views/expenditure_articles/_form.html.erb
<%= bootstrap_form_for @expenditure_article do |f| %>
  <%= f.alert_message 'Vă rog să rezolvați erorile de mai jos:' %>

  <div class="col-12 col-sm-8 col-md-6 col-lg-4">
    <%= f.text_field :code %>
    <%= f.text_field :name %>
    <%= f.text_field :expenditure_category_code %>
    <%= f.text_field :commitment_category_code %>

    <%= f.submit f.object.persisted? ? 'Salvează' : 'Adaugă' %>
  </div>
<% end %>

app/views/expenditure_articles/edit.html.erb
<% content_for :title, 'Editare articol de cheltuială' %>

<h1>Editează un articol de cheltuială existent</h1>

<p><%= link_to 'Înapoi la lista de articole de cheltuială', expenditure_articles_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>

app/views/expenditure_articles/import.html.erb
<% content_for :title, 'Importă articole de cheltuială' %>

<h1>Importă articole de cheltuială</h1>

<p><%= link_to 'Înapoi la lista de articole de cheltuială', expenditure_articles_path, class: 'btn btn-light' %></p>

<%= render partial: 'flashes' %>

<%= bootstrap_form_with url: import_upload_expenditure_articles_path, method: :post do |form| %>
  <%= form.file_field :file,
                      label: 'Fișier Excel cu articolele de cheltuială',
                      accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>

  <%= form.submit 'Importă' %>
<% end %>

app/views/expenditure_articles/index.html.erb
<% content_for :title, 'Articole de cheltuială' %>

<h1>Articole de cheltuială</h1>

<% can_modify_expenditure_articles = current_user_has_permission? 'ExpenditureArticle.Edit' %>

<p><%= link_to 'Înapoi la pagina principală', root_path, class: 'btn btn-light' %></p>
<% if can_modify_expenditure_articles %>
  <p><%= link_to 'Adaugă un articol de cheltuială nou', new_expenditure_article_path, class: 'btn btn-primary' %></p>
<% end %>
<p><%= link_to 'Exportă lista de articole de cheltuială', export_download_expenditure_articles_path,
               class: 'btn btn-success',
               download: true, data: { turbo: false } %></p>
<% if can_modify_expenditure_articles %>
  <p><%= link_to 'Importă articole de cheltuială din Excel', import_expenditure_articles_path,
                 class: 'btn btn-success' %></p>
<% end %>

<%= render partial: 'flashes' %>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th scope="col">Nr. crt.</th>
      <th scope="col">Cod</th>
      <th scope="col">Denumire</th>
      <th scope="col">Indicator cheltuieli</th>
      <th scope="col">Indicator angajamente</th>
      <% if can_modify_expenditure_articles %>
        <th scope="col">Acțiuni</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @expenditure_articles.each_with_index do |expenditure_article, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= expenditure_article.code %></td>
        <td><%= expenditure_article.name %></td>
        <td><%= expenditure_article.expenditure_category_code %></td>
        <td><%= expenditure_article.commitment_category_code %></td>
        <% if can_modify_expenditure_articles %>
          <td class="text-nowrap">
            <%= link_to 'Editează', edit_expenditure_article_path(expenditure_article.id),
                        class: 'btn btn-warning' %>
            <%= link_to 'Șterge', expenditure_article_path(expenditure_article.id), method: :delete,
                        data: { confirm: 'Ești sigur că vrei să ștergi acest articol de cheltuială?' },
                        class: 'btn btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/expenditure_articles/new.html.erb
<% content_for :title, 'Adaugare articol de cheltuială' %>

<h1>Adaugă un articol de cheltuială nou</h1>

<p><%= link_to 'Înapoi la lista de articole de cheltuială', expenditure_articles_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>