config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: %i[index new edit create update]

  resources :financing_sources do
    get 'export', to: 'financing_sources#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'financing_sources#import', as: :import, on: :collection
    post 'import', to: 'financing_sources#import_upload', as: :import_upload, on: :collection
  end

  resources :project_categories

  resources :expenditure_articles do
    get 'export', to: 'expenditure_articles#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'expenditure_articles#import', as: :import, on: :collection
    post 'import', to: 'expenditure_articles#import_upload', as: :import_upload, on: :collection
  end

  resources :payment_types do
    get 'export', to: 'payment_types#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'payment_types#import', as: :import, on: :collection
    post 'import', to: 'payment_types#import_upload', as: :import_upload, on: :collection
  end

  resources :expenditures, only: %i[index new edit create update] do
    get 'duplicate', to: 'expenditures#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'expenditures#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'expenditures#import', as: :import
      post 'import', to: 'expenditures#import_upload', as: :import_upload
      get 'find_matching_invoices', to: 'expenditures#find_matching_invoices',
                                    as: :find_matching_invoices,
                                    defaults: { format: :json }
      get 'find_matching_beneficiaries', to: 'expenditures#find_matching_beneficiaries',
                                         as: :find_matching_beneficiaries,
                                         defaults: { format: :json }
    end
  end

  resources :commitments, only: %i[index new edit create update] do
    get 'duplicate', to: 'commitments#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'commitments#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'commitments#import', as: :import
      post 'import', to: 'commitments#import_upload', as: :import_upload
    end
  end

  resources :settings, only: %i[index] do
    post 'update', to: 'settings#update', as: :update, on: :collection
  end

  get :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report', as: :generate_pfc_activity_report
  post :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report'
  get :pfc_activity_report, to: 'reports#pfc_activity_report', as: :download_pfc_activity_report, format: 'xlsx'

  resources :audit_events, only: [:index]
end

app/models/financing_source.rb
# frozen_string_literal: true

class FinancingSource < ApplicationRecord
  include ImportMatchable

  validates :name, presence: true, uniqueness: true

  normalizes :name, with: ->(name) { name.strip }

  has_many :expenditures, dependent: :restrict_with_error
  has_many :commitment_financing_source_associations, dependent: :restrict_with_error
  has_many :commitments, through: :commitment_financing_source_associations, dependent: :restrict_with_error
end

app/controllers/financing_sources_controller.rb
# frozen_string_literal: true

class FinancingSourcesController < ApplicationController
  before_action -> { require_permission 'FinancingSource.View' }, only: %i[index export_download]
  before_action -> { require_permission 'FinancingSource.Create' }, only: %i[new create import import_upload]
  before_action -> { require_permission 'FinancingSource.Edit' }, only: %i[edit update]
  before_action -> { require_permission 'FinancingSource.Delete' }, only: %i[destroy]

  def index
    @financing_sources = FinancingSource.order(name: :asc)
  end

  def new
    @financing_source = FinancingSource.new
  end

  def edit
    financing_source_id = params.require(:id)
    @financing_source = FinancingSource.find(financing_source_id)
  end

  def create
    @financing_source = FinancingSource.new financing_source_params

    successfully_saved = false
    FinancingSource.transaction do
      successfully_saved = @financing_source.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :insert,
          target_table: :financing_sources,
          target_object_id: @financing_source.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost salvată cu succes o nouă sursă de finanțare cu denumirea '#{@financing_source.name}'"
      redirect_to financing_sources_path
    else
      flash[:alert] = 'Nu s-a putut salva noua sursă de finanțare. Verificați erorile și încercați din nou.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    financing_source_id = params.require(:id)
    @financing_source = FinancingSource.find(financing_source_id)

    @financing_source.assign_attributes financing_source_params

    successfully_saved = false
    FinancingSource.transaction do
      successfully_saved = @financing_source.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :update,
          target_table: :financing_sources,
          target_object_id: @financing_source.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost actualizată cu succes sursa de finanțare cu denumirea '#{@financing_source.name}'"
      redirect_to financing_sources_path
    else
      flash[:alert] = 'Nu s-au putut salva modificările la sursa de finanțare. Verificați erorile și încercați din nou.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    financing_source_id = params.require(:id)
    @financing_source = FinancingSource.find(financing_source_id)

    successfully_deleted = false
    FinancingSource.transaction do
      successfully_deleted = @financing_source.destroy

      if successfully_deleted
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :delete,
          target_table: :financing_sources,
          target_object_id: @financing_source.id
        )
      end
    end

    if successfully_deleted
      flash[:notice] = "A fost ștearsă cu succes sursa de finanțare cu denumirea '#{@financing_source.name}'"
    else
      flash[:alert] = "Nu s-a putut șterge sursa de finanțare: #{@financing_source.errors.full_messages.join(', ')}."
    end

    redirect_to financing_sources_path
  end

  def export_download
    @financing_sources = FinancingSource.order(name: :asc)
    date = Time.current.strftime('%Y-%m-%d')

    render xlsx: 'export', template: 'financing_sources/export',
           disposition: 'attachment', filename: "Export surse de finanțare #{date}.xlsx"
  end

  def import; end

  def import_upload
    uploaded_file = params.require(:file)
    spreadsheet = Roo::Spreadsheet.open(uploaded_file)
    sheet = spreadsheet.sheet(0)

    total_count = 0
    FinancingSource.transaction do
      (2..sheet.last_row).each do |row_index|
        row = sheet.row row_index

        name = row[0].strip

        financing_source = FinancingSource.find_or_initialize_by(name:)
        financing_source.import_code = row[1]&.strip || ''

        raise ImportError.new(row_index, financing_source.errors.full_messages.join(', ')) unless financing_source.save

        if financing_source.previously_new_record?
          AuditEvent.create!(
            timestamp: DateTime.now,
            user: current_user,
            action: :insert,
            target_table: :financing_sources,
            target_object_id: financing_source.id
          )
        end

        total_count += 1
      end
    end

    flash[:notice] = "S-au importat/actualizat cu succes #{total_count} surse de finanțare!"
    redirect_to financing_sources_path
  rescue ImportError => e
    flash.now[:alert] = e.to_s
    render :import
  end

  private

  def financing_source_params
    params.expect(financing_source: %i[name import_code])
  end
end

app/views/financing_sources/_form.html.erb
<%= bootstrap_form_for @financing_source do |f| %>
  <%= f.alert_message 'Vă rog să rezolvați erorile de mai jos:' %>

  <div class="col-12 col-sm-8 col-md-6 col-lg-4">
    <%= f.text_field :name %>

    <%= f.text_field :import_code %>

    <%= f.submit f.object.persisted? ? 'Salvează' : 'Adaugă' %>
  </div>
<% end %>

app/views/financing_sources/edit.html.erb
<% content_for :title, 'Editare sursă de finanțare' %>

<h1>Editează o sursă de finanțare existentă</h1>

<p><%= link_to 'Înapoi la lista de surse de finanțare', financing_sources_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>

app/views/financing_sources/import.html.erb
<% content_for :title, 'Import surse de finanțare' %>

<h1>Importă surse de finanțare</h1>

<p><%= link_to 'Înapoi la lista de surse de finanțare', financing_sources_path, class: 'btn btn-light' %></p>

<%= render partial: 'flashes' %>

<%= bootstrap_form_with url: import_upload_financing_sources_path, method: :post do |form| %>
  <%= form.file_field :file,
                      label: 'Fișier Excel cu sursele de finanțare',
                      accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>

  <%= form.submit 'Importă' %>
<% end %>

app/views/financing_sources/index.html.erb
<% content_for :title, 'Surse de finanțare' %>

<h1>Surse de finanțare (centre de cost)</h1>

<% can_modify_financing_sources = current_user_has_permission? 'FinancingSource.Edit' %>

<p><%= link_to 'Înapoi la pagina principală', root_path, class: 'btn btn-light' %></p>
<% if can_modify_financing_sources %>
  <p><%= link_to 'Adaugă o sursă de finanțare nouă', new_financing_source_path, class: 'btn btn-primary' %></p>
<% end %>
<p><%= link_to 'Exportă lista de surse de finanțare', export_download_financing_sources_path,
               class: 'btn btn-success',
               download: true, data: { turbo: false } %></p>
<% if can_modify_financing_sources %>
  <p><%= link_to 'Importă surse de finanțare din Excel', import_financing_sources_path,
                 class: 'btn btn-success' %></p>
<% end %>

<%= render partial: 'flashes' %>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th scope="col">Nr. crt.</th>
      <th scope="col">Denumire</th>
      <th scope="col">Cod de import</th>
      <% if can_modify_financing_sources %>
        <th scope="col">Acțiuni</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @financing_sources.each_with_index do |financing_source, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= financing_source.name %></td>
        <td>
          <code><%= financing_source.import_code %></code>
        </td>
        <% if can_modify_financing_sources %>
          <td>
            <%= link_to 'Editează', edit_financing_source_path(financing_source.id), class: 'btn btn-warning' %>
            <%= link_to 'Șterge', financing_source_path(financing_source.id), method: :delete,
                        class: 'btn btn-danger',
                        data: { confirm: 'Ești sigur că vrei să ștergi această sursă de finanțare?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/financing_sources/new.html.erb
<% content_for :title, 'Adăugare sursă de finanțare' %>

<h1>Adaugă o sursă de finanțare nouă</h1>

<p><%= link_to 'Înapoi la lista de surse de finanțare', financing_sources_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>