config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: %i[index new edit create update]

  resources :financing_sources do
    get 'export', to: 'financing_sources#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'financing_sources#import', as: :import, on: :collection
    post 'import', to: 'financing_sources#import_upload', as: :import_upload, on: :collection
  end

  resources :project_categories

  resources :expenditure_articles do
    get 'export', to: 'expenditure_articles#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'expenditure_articles#import', as: :import, on: :collection
    post 'import', to: 'expenditure_articles#import_upload', as: :import_upload, on: :collection
  end

  resources :payment_types do
    get 'export', to: 'payment_types#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'payment_types#import', as: :import, on: :collection
    post 'import', to: 'payment_types#import_upload', as: :import_upload, on: :collection
  end

  resources :expenditures, only: %i[index new edit create update] do
    get 'duplicate', to: 'expenditures#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'expenditures#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'expenditures#import', as: :import
      post 'import', to: 'expenditures#import_upload', as: :import_upload
      get 'find_matching_invoices', to: 'expenditures#find_matching_invoices',
                                    as: :find_matching_invoices,
                                    defaults: { format: :json }
      get 'find_matching_beneficiaries', to: 'expenditures#find_matching_beneficiaries',
                                         as: :find_matching_beneficiaries,
                                         defaults: { format: :json }
    end
  end

  resources :commitments, only: %i[index new edit create update] do
    get 'duplicate', to: 'commitments#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'commitments#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'commitments#import', as: :import
      post 'import', to: 'commitments#import_upload', as: :import_upload
    end
  end

  resources :settings, only: %i[index] do
    post 'update', to: 'settings#update', as: :update, on: :collection
  end

  get :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report', as: :generate_pfc_activity_report
  post :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report'
  get :pfc_activity_report, to: 'reports#pfc_activity_report', as: :download_pfc_activity_report, format: 'xlsx'

  resources :audit_events, only: [:index]
end

app/controllers/payment_types_controller.rb
# frozen_string_literal: true

class PaymentTypesController < ApplicationController
  before_action -> { require_permission 'PaymentType.View' }, only: %i[index export_download]
  before_action -> { require_permission 'PaymentType.Create' }, only: %i[new create import import_upload]
  before_action -> { require_permission 'PaymentType.Edit' }, only: %i[edit update]
  before_action -> { require_permission 'PaymentType.Delete' }, only: %i[destroy]

  def index
    @payment_types = PaymentType.order(name: :asc)
  end

  def new
    @payment_type = PaymentType.new
  end

  def edit
    payment_type_id = params.require(:id)
    @payment_type = PaymentType.find(payment_type_id)
  end

  def create
    @payment_type = PaymentType.new payment_type_params

    successfully_saved = false
    PaymentType.transaction do
      successfully_saved = @payment_type.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :insert,
          target_table: :payment_types,
          target_object_id: @payment_type.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost salvat cu succes un nou tip de plată cu denumirea '#{@payment_type.name}'"
      redirect_to payment_types_path
    else
      flash[:alert] = 'Nu s-a putut salva noul tip de plată. Verificați erorile și încercați din nou.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    payment_type_id = params.require(:id)
    @payment_type = PaymentType.find(payment_type_id)

    @payment_type.assign_attributes payment_type_params

    successfully_saved = false
    PaymentType.transaction do
      successfully_saved = @payment_type.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :update,
          target_table: :payment_types,
          target_object_id: @payment_type.id
        )
      end
    end

    if successfully_saved
      flash[:notice] = "A fost actualizat cu succes tipul de plată cu denumirea '#{@payment_type.name}'"
      redirect_to payment_types_path
    else
      flash[:alert] = 'Nu s-au putut salva modificările la tipurile de plată. Verificați erorile și încercați din nou.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    payment_type_id = params.require(:id)
    @payment_type = PaymentType.find(payment_type_id)

    successfully_deleted = false
    PaymentType.transaction do
      successfully_deleted = @payment_type.destroy

      if successfully_deleted
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :delete,
          target_table: :payment_types,
          target_object_id: @payment_type.id
        )
      end
    end

    if successfully_deleted
      flash[:notice] = "A fost șters cu succes tipul de plată cu denumirea '#{@payment_type.name}'"
    else
      flash[:alert] = "Nu s-a putut șterge tipul de plată: #{@payment_type.errors.full_messages.join(', ')}."
    end

    redirect_to payment_types_path
  end

  def export_download
    @payment_types = PaymentType.order(name: :asc)
    date = Time.current.strftime('%Y-%m-%d')
    render xlsx: 'export', template: 'payment_types/export',
           disposition: 'attachment', filename: "Export tipuri de plăți #{date}.xlsx"
  end

  def import; end

  def import_upload
    uploaded_file = params.require(:file)
    spreadsheet = Roo::Spreadsheet.open(uploaded_file)
    sheet = spreadsheet.sheet(0)

    total_count = 0
    PaymentType.transaction do
      (2..sheet.last_row).each do |row_index|
        row = sheet.row row_index

        name = row[0].strip

        payment_type = PaymentType.find_or_initialize_by(name:)

        raise ImportError.new(row_index, payment_type.errors.full_messages.join(', ')) unless payment_type.save

        if payment_type.previously_new_record?
          AuditEvent.create!(
            timestamp: DateTime.now,
            user: current_user,
            action: :insert,
            target_table: :payment_types,
            target_object_id: payment_type.id
          )
        end

        total_count += 1
      end
    end

    flash[:notice] = "S-au importat/actualizat cu succes #{total_count} tipuri de plăți!"
    redirect_to payment_types_path
  rescue ImportError => e
    flash.now[:alert] = e.to_s
    render :import
  end

  private

  def payment_type_params
    params.expect(payment_type: [:name])
  end
end

app/views/payment_types/_form.html.erb
<%= bootstrap_form_for @payment_type do |f| %>
  <%= f.alert_message 'Vă rog să rezolvați erorile de mai jos:' %>

  <div class="col-12 col-sm-8 col-md-6 col-lg-4">
    <%= f.text_field :name %>

    <%= f.submit f.object.persisted? ? 'Salvează' : 'Adaugă' %>
  </div>
<% end %>

app/views/payment_types/edit.html.erb
<% content_for :title, 'Editare tip de plată' %>

<h1>Editează un tip de plată existent</h1>

<p><%= link_to 'Înapoi la lista de tipuri de plăți', payment_types_path, class: 'btn btn-light' %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>

app/views/payment_types/import.html.erb
<% content_for :title, 'Import tipuri de plăți' %>

<h1>Importă tipuri de plăți</h1>

<p><%= link_to 'Înapoi la lista de tipuri de plăți', payment_types_path %></p>

<%= render partial: 'flashes' %>

<%= bootstrap_form_with url: import_upload_payment_types_path, method: :post do |form| %>
  <%= form.file_field :file,
                      label: 'Fișier Excel cu tipurile de plăți',
                      accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>

  <%= form.submit 'Importă' %>
<% end %>

app/views/payment_types/index.html.erb
<% content_for :title, 'Tipuri de plăți' %>

<h1>Tipuri de plăți</h1>

<% can_modify_payment_types = current_user_has_permission? 'PaymentType.Edit' %>

<p><%= link_to 'Înapoi la pagina principală', root_path, class: 'btn btn-light' %></p>
<% if can_modify_payment_types %>
  <p><%= link_to 'Adaugă un tip de plată nou', new_payment_type_path, class: 'btn btn-primary' %></p>
<% end %>
<p><%= link_to 'Exportă lista de tipuri de plăți', export_download_payment_types_path,
               class: 'btn btn-success',
               download: true, data: { turbo: false } %></p>
<% if can_modify_payment_types %>
  <p><%= link_to 'Importă tipuri de plăți din Excel', import_payment_types_path, class: 'btn btn-success' %></p>
<% end %>

<%= render partial: 'flashes' %>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th scope="col">Nr. crt.</th>
      <th scope="col">Denumire</th>
      <% if can_modify_payment_types %>
        <th scope="col">Acțiuni</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @payment_types.each_with_index do |payment_type, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= payment_type.name %></td>
        <% if can_modify_payment_types %>
          <td>
            <%= link_to 'Editează', edit_payment_type_path(payment_type.id), class: 'btn btn-warning' %>
            <%= link_to 'Șterge', payment_type_path(payment_type.id), method: :delete, class: 'btn btn-danger',
                        data: { confirm: 'Ești sigur că vrei să ștergi acest tip de plată?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/payment_types/new.html.erb
<h1>Adaugă un tip de plată nou</h1>

<p><%= link_to 'Înapoi la lista de tipuri de plăți', payment_types_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>