config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/sign_out', to: 'sessions#destroy', as: :sign_out

  resources :users, only: %i[index new edit create update]

  resources :financing_sources do
    get 'export', to: 'financing_sources#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'financing_sources#import', as: :import, on: :collection
    post 'import', to: 'financing_sources#import_upload', as: :import_upload, on: :collection
  end

  resources :project_categories

  resources :expenditure_articles do
    get 'export', to: 'expenditure_articles#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'expenditure_articles#import', as: :import, on: :collection
    post 'import', to: 'expenditure_articles#import_upload', as: :import_upload, on: :collection
  end

  resources :payment_types do
    get 'export', to: 'payment_types#export_download', as: :export_download, on: :collection, format: 'xlsx'
    get 'import', to: 'payment_types#import', as: :import, on: :collection
    post 'import', to: 'payment_types#import_upload', as: :import_upload, on: :collection
  end

  resources :expenditures, only: %i[index new edit create update] do
    get 'duplicate', to: 'expenditures#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'expenditures#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'expenditures#import', as: :import
      post 'import', to: 'expenditures#import_upload', as: :import_upload
      get 'find_matching_invoices', to: 'expenditures#find_matching_invoices',
                                    as: :find_matching_invoices,
                                    defaults: { format: :json }
      get 'find_matching_beneficiaries', to: 'expenditures#find_matching_beneficiaries',
                                         as: :find_matching_beneficiaries,
                                         defaults: { format: :json }
    end
  end

  resources :commitments, only: %i[index new edit create update] do
    get 'duplicate', to: 'commitments#duplicate', as: :duplicate, on: :member
    collection do
      get 'export', to: 'commitments#export_download', as: :export_download, format: 'xlsx'
      get 'import', to: 'commitments#import', as: :import
      post 'import', to: 'commitments#import_upload', as: :import_upload
    end
  end

  resources :settings, only: %i[index] do
    post 'update', to: 'settings#update', as: :update, on: :collection
  end

  get :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report', as: :generate_pfc_activity_report
  post :generate_pfc_activity_report, to: 'reports#generate_pfc_activity_report'
  get :pfc_activity_report, to: 'reports#pfc_activity_report', as: :download_pfc_activity_report, format: 'xlsx'

  resources :audit_events, only: [:index]
end

app/models/commitment.rb
# frozen_string_literal: true

class Commitment < RegistryRecord
  validates :expenditure_article, :financing_sources_ids, :document_number, :partner, :value,
            presence: true, unless: :cancelled?

  has_many :commitment_financing_source_associations, dependent: :destroy
  has_many :financing_sources, through: :commitment_financing_source_associations
  belongs_to :expenditure_article, optional: true

  belongs_to :created_by_user, class_name: 'User'
  belongs_to :updated_by_user, class_name: 'User'

  before_validation -> { @financing_sources_ids ||= financing_sources.map(&:id) }

  def financing_sources_ids
    @financing_sources_ids ||= financing_sources.pluck(&:id)
  end

  def financing_sources_ids=(ids)
    self.financing_sources = []
    @financing_sources_ids = []
    ids.each do |id|
      next if id.blank?

      financing_sources << FinancingSource.find(id)
      @financing_sources_ids << id
    end
  end
end

app/models/expenditure.rb
# frozen_string_literal: true

class Expenditure < RegistryRecord
  validates :financing_source, :expenditure_article, :payment_type, :value,
            presence: true, unless: :cancelled?
  # Some imported records might not have a beneficiary listed
  validates :beneficiary, presence: true, unless: -> { cancelled? || imported? }

  validate :ordinance_date_before_registration_date, on: :create, unless: -> { cancelled? || imported? }

  belongs_to :financing_source, optional: true
  belongs_to :project_category, optional: true
  belongs_to :expenditure_article, optional: true
  belongs_to :payment_type, optional: true

  belongs_to :created_by_user, class_name: 'User'
  belongs_to :updated_by_user, class_name: 'User'

  attr_accessor :imported

  def imported?
    !!@imported
  end

  private

  def ordinance_date_before_registration_date
    return unless registration_date.present? && ordinance_date.present?
    return if ordinance_date <= registration_date

    errors.add(:registration_date, 'nu poate fi înainte de data ordonanțării')
  end
end

app/controllers/expenditures_controller.rb
# frozen_string_literal: true

class ExpendituresController < ApplicationController
  include Filtrable

  before_action -> { require_permission 'Expenditure.View' },
                only: %i[index export_download find_matching_beneficiaries find_matching_invoices]
  before_action -> { require_permission 'Expenditure.Create' }, only: %i[new duplicate create]
  before_action -> { require_permission 'Expenditure.Edit' }, only: %i[edit update]
  before_action -> { require_permission 'Expenditure.Import' }, only: %i[import import_upload]

  def index
    @layout_without_container = true

    @expenditures = Expenditure.order('year desc, registration_number desc')

    include_dependent_entities

    if cookies[:show_filter_form].present?
      @show_filter_form = ActiveRecord::Type::Boolean.new.cast(cookies[:show_filter_form])
    end

    apply_filters

    @paginated_expenditures = @expenditures.paginate(
      page: params[:page],
      per_page: 10
    )
  end

  def new
    @expenditure = Expenditure.new
    @expenditure.year = Setting.current_year
    @expenditure.registration_date = Time.zone.today
    @expenditure.created_by_user = current_user
  end

  def edit
    @expenditure = Expenditure.find(params[:id])
    @expenditure.updated_by_user = current_user
  end

  def duplicate
    @expenditure = Expenditure.find(params[:id]).dup
    @expenditure.registration_number = nil
    @expenditure.created_by_user = current_user
    @expenditure.updated_by_user = current_user
  end

  def create
    @expenditure = Expenditure.new expenditure_params
    @expenditure.year = Setting.current_year
    @expenditure.created_by_user = current_user
    @expenditure.updated_by_user = current_user

    successfully_saved = false
    Expenditure.transaction do
      last_registration_number = Expenditure.where(year: @expenditure.year).maximum(:registration_number)
      last_registration_number ||= 0
      @expenditure.registration_number = last_registration_number + 1

      successfully_saved = @expenditure.save

      if successfully_saved
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :insert,
          target_table: :expenditures,
          target_object_id: "#{@expenditure.registration_number}/#{@expenditure.year}"
        )
      end
    end

    if successfully_saved
      flash[:notice] = t('expenditures.update.success_message',
                         registration_number: @expenditure.registration_number,
                         year: @expenditure.year)
      redirect_to expenditures_path
    else
      flash[:alert] = t 'expenditures.update.error_message'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @expenditure = Expenditure.find(params[:id])
    @expenditure.update expenditure_params
    @expenditure.updated_by_user = current_user

    Expenditure.transaction do
      if @expenditure.save
        AuditEvent.create!(
          timestamp: DateTime.now,
          user: current_user,
          action: :update,
          target_table: :expenditures,
          target_object_id: "#{@expenditure.registration_number}/#{@expenditure.year}"
        )

        flash[:notice] = t('expenditures.update.success_message',
                           registration_number: @expenditure.registration_number,
                           year: @expenditure.year)
        redirect_to expenditures_path
      else
        flash[:alert] = t 'expenditures.update.error_message'
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def import; end

  def import_upload
    if params[:file].blank?
      flash[:alert] = t 'expenditures.import.missing_file'
      return redirect_to import_expenditures_path
    end

    uploaded_file = params.require(:file)
    spreadsheet = Roo::Spreadsheet.open(uploaded_file)
    sheet = spreadsheet.sheet(0)

    @financing_sources = FinancingSource.with_import_code.to_a
    @project_categories = ProjectCategory.with_import_code.to_a

    saved_count = 0
    error_count = 0
    @error_messages = []
    Expenditure.transaction do
      (2..sheet.last_row).each do |row_index|
        row = sheet.row row_index

        # We've reached the end of the filled-in table
        break if row[1].blank? && row[2].blank?

        begin
          expenditure = parse_expenditure row_index, row

          if expenditure.save
            saved_count += 1
          else
            raise ImportError.new(
              row_index,
              "nu s-a putut salva înregistrarea: #{expenditure.errors.full_messages.join(', ')}."
            )
          end
        rescue ImportError => e
          @error_messages << e.to_s
          error_count += 1
        end

        # Exit if we've already accumulated too many errors
        break if error_count > ImportError::MAX_ERRORS
      end

      # Roll back the transaction if some records couldn't be saved.
      raise ActiveRecord::Rollback if error_count.positive?
    end

    if error_count.positive?
      flash.now[:alert] = 'Nu s-au putut importa cu succes toate înregistrările din cauza unor erori.'
      render :import
    else
      flash[:notice] = "S-au importat cu succes #{saved_count} de înregistrări!"
      redirect_to expenditures_path
    end
  end

  def export_download
    require_permission 'Expenditure.View'

    @expenditures = Expenditure.order('year, registration_number')

    include_dependent_entities
    apply_filters

    date = Time.current.strftime('%Y-%m-%d')
    render xlsx: 'export', template: 'expenditures/export',
           disposition: 'attachment', filename: "Export cheltuieli #{date}.xlsx"
  end

  def find_matching_invoices
    term = params[:term]

    return render json: [] if term.blank? || term.size < 2

    matching_invoices = Expenditure.where('invoice LIKE ?', "%#{term}%")
                                   .distinct
                                   .limit(15)
                                   .pluck(:invoice)

    render json: matching_invoices
  end

  def find_matching_beneficiaries
    term = params[:term]

    return render json: [] if term.blank? || term.size < 2

    matching_beneficiaries = Expenditure.where('beneficiary LIKE ?', "%#{term}%")
                                        .distinct
                                        .limit(15)
                                        .pluck(:beneficiary)

    matching_partners = Commitment.where('partner LIKE ?', "%#{term}%")
                                  .distinct
                                  .limit(15)
                                  .pluck(:partner)

    matches = matching_beneficiaries + matching_partners
    matches.uniq!

    render json: matches
  end

  private

  def expenditure_params
    params.expect(
      expenditure: %i[
        registration_date
        financing_source_id
        project_category_id
        project_details
        expenditure_article_id
        details
        procurement_type
        ordinance_number
        ordinance_date
        value
        payment_type_id
        beneficiary
        invoice
        noncompliance
        remarks
      ]
    )
  end

  def include_dependent_entities
    relation_names = %i[
      financing_source project_category expenditure_article payment_type
      created_by_user updated_by_user
    ]
    @expenditures = @expenditures.references(relation_names).includes(relation_names)
  end

  def apply_filters
    @any_filters_applied = false

    @expenditures = apply_field_value_filter @expenditures, :registration_number
    @expenditures = apply_field_value_filter @expenditures, :year

    if params[:start_date].present?
      start_date = Date.strptime(params[:start_date], '%d.%m.%Y')
      @expenditures = @expenditures.where(registration_date: start_date..)
      @any_filters_applied = true
    end

    if params[:end_date].present?
      end_date = Date.strptime(params[:end_date], '%d.%m.%Y')
      @expenditures = @expenditures.where(registration_date: ..end_date)
      @any_filters_applied = true
    end

    if params[:expenditure_category_code].present?
      @expenditures = @expenditures.where(
        expenditure_article: {
          expenditure_category_code: params[:expenditure_category_code]
        }
      )
      @any_filters_applied = true
    end

    @expenditures = apply_ids_filter @expenditures,
                                     :financing_source_ids,
                                     :financing_source_id

    @expenditures = apply_ids_filter @expenditures,
                                     :project_category_ids,
                                     :project_category_id

    @expenditures = apply_ids_filter @expenditures,
                                     :expenditure_article_ids,
                                     :expenditure_article_id

    @expenditures = apply_exclude_cash_receipts_filter @expenditures

    @expenditures = apply_string_field_filter @expenditures, :project_details
    @expenditures = apply_string_field_filter @expenditures, :details
    @expenditures = apply_string_field_filter @expenditures, :procurement_type
    @expenditures = apply_string_field_filter @expenditures, :ordinance_number

    if params[:ordinance_date].present?
      ordinance_date = Date.strptime(params[:ordinance_date], '%d.%m.%Y')
      @expenditures = @expenditures.where(ordinance_date:)
      @any_filters_applied = true
    end

    @expenditures = apply_value_range_filter @expenditures

    @expenditures = apply_ids_filter @expenditures,
                                     :payment_type_ids,
                                     :payment_type_id,
                                     :payment_type_ids

    @expenditures = apply_string_field_filter @expenditures, :beneficiary
    @expenditures = apply_string_field_filter @expenditures, :invoice
    @expenditures = apply_string_field_filter @expenditures, :noncompliance

app/views/expenditures/_form.html.erb
<%= bootstrap_form_for @expenditure do |f| %>
  <%= f.alert_message 'Vă rog să rezolvați erorile de mai jos:' %>

  <div class="col-12 col-sm-8 col-md-6 col-lg-4">
    <%= f.number_field :year, disabled: true %>

    <%= f.text_field :registration_date,
                     # TODO: come up with a better way to handle date formatting
                     value: f.object.registration_date&.strftime('%d.%m.%Y'),
                     data: { datepicker: true, max_date: Time.zone.today.strftime('%d.%m.%Y') } %>

    <%= f.select :financing_source_id,
                 FinancingSource.order(:name).map { |financing_source|
                   [financing_source.name, financing_source.id]
                 },
                 { include_blank: 'Selectează o sursă de finanțare...' },
                 { data: { use_select2: true } }
    %>

    <%= f.select :project_category_id,
                 ProjectCategory.order(:name).map { |project_category|
                   [project_category.name, project_category.id]
                 },
                 { include_blank: 'Selectează o categorie de proiect...' },
                 { data: { use_select2: true } }
    %>

    <%= f.text_area :project_details %>

    <%= f.select :expenditure_article_id,
                 ExpenditureArticle.order(:code).map { |expenditure_article|
                   ["#{expenditure_article.code} - #{expenditure_article.name}", expenditure_article.id]
                 },
                 { include_blank: 'Selectează articolul de cheltuială...' },
                 { data: { use_select2: true } }
    %>

    <%= f.text_area :details %>

    <%= f.text_field :procurement_type %>

    <%= f.text_field :ordinance_number %>
    <%= f.text_field :ordinance_date,
                     value: f.object.ordinance_date&.strftime('%d.%m.%Y'),
                     data: { datepicker: true, max_date: Time.zone.today.strftime('%d.%m.%Y') } %>

    <%= f.number_field :value, step: '0.01' %>

    <%= f.select :payment_type_id,
                 PaymentType.order(:name).map { |payment_type|
                   [payment_type.name, payment_type.id]
                 },
                 { include_blank: 'Selectează tipul de plată...' },
                 { data: { use_select2: true } }
    %>

    <%= f.text_field :beneficiary %>

    <%= f.text_field :invoice %>

    <%= f.text_area :noncompliance %>

    <%= f.text_area :remarks %>

    <%= f.text_field :created_by_user, value: f.object.created_by_user.full_name, disabled: true %>

    <% if f.object.persisted? %>
      <%= f.text_field :updated_by_user, value: f.object.updated_by_user.full_name, disabled: true %>
    <% end %>

    <%= f.submit f.object.persisted? ? 'Salvează' : 'Adaugă' %>
  </div>
<% end %>

app/views/expenditures/duplicate.html.erb
<% content_for :title, "Duplicare cheltuială #{@expenditure.full_identifier}" %>

<h1>Duplică o cheltuială existentă</h1>

<p><%= link_to 'Înapoi la registrul de cheltuieli', expenditures_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>

app/views/expenditures/edit.html.erb
<% content_for :title, "Editare cheltuială #{@expenditure.full_identifier}" %>

<h1>Editează o cheltuială existentă</h1>

<p><%= link_to 'Înapoi la registrul de cheltuieli', expenditures_path %></p>

<%= render partial: 'flashes' %>

<%= render partial: 'form' %>

app/views/expenditures/import.html.erb
<% content_for :title, 'Importare cheltuieli' %>

<h1>Importă cheltuieli</h1>

<p>
  <%= link_to 'Înapoi la registrul de cheltuieli', expenditures_path, class: 'btn btn-light' %>
</p>

<p>
  Pe această pagină puteți importa cheltuieli dintr-un registru în format Excel.
  Asigurați-vă că fișierul conține doar înregistrările care vreți să fie aduse în aplicație. Ștergeți celelalte
  sheet-uri și încărcați fișierul în formularul de mai jos.

  Aplicația vă va semnala potențialele erori care previn importarea corectă a datelor.
</p>

<%= render partial: 'flashes' %>

<% if @error_messages&.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @error_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_with url: import_upload_expenditures_path, method: :post do |form| %>
  <%= form.file_field :file,
                      label: 'Fișier Excel cu registrul de cheltuieli',
                      accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>

  <%= form.submit 'Importă' %>
<% end %>

app/views/expenditures/index.html.erb
<% content_for :title, 'Cheltuieli' %>

<% can_modify_expenditures = current_user_has_permission? 'Expenditure.Edit' %>

<div class="container">
  <h1 class="mt-5 mb-3">Registru cheltuieli</h1>

  <div class="row">
    <div class="col">
      <p><%= link_to 'Înapoi la pagina principală', root_path, class: 'btn btn-light' %></p>
      <p><%= link_to 'Adaugă o cheltuială nouă', new_expenditure_path, class: 'btn btn-primary' %></p>
      <% if can_modify_expenditures %>
        <p><%= link_to 'Importă cheltuieli din Excel', import_expenditures_path, class: 'btn btn-success' %></p>
      <% end %>
      <p><%= link_to 'Exportă lista de cheltuieli ca Excel',
                     export_download_expenditures_path(**request.query_parameters),
                     download: true, class: 'btn btn-success', data: { turbo: false } %></p>
      <p>
        <%= button_tag type: 'button', class: 'btn btn-primary',
                       data: { bs_toggle: 'collapse', bs_target: '#filter-form' },
                       aria: { expanded: @show_filter_form, controls: 'filter-form' } do %>
          Caută / filtrează înregistrări
        <% end %>
      </p>
    </div>

    <section class="col">
      <%= render partial: 'application/statistics', locals: { collection: @expenditures } %>
    </section>
  </div>

  <%= render partial: 'flashes' %>

  <div class="mx-10">
    <%= bootstrap_form_with method: :get, layout: :inline, id: 'filter-form',
                            html: { class: 'border my-3 pb-2 collapse' + (@show_filter_form ? ' show' : '') } do |form| %>
      <%= form.text_field :registration_number,
                          value: params[:registration_number],
                          label: 'Număr de înregistrare' %>
      <%= form.text_field :year,
                          value: params[:year] || current_year,
                          label: 'Anul', wrapper: { style: 'width: 100px' } %>
      <%= render partial: 'application/filters/start_end_date_filters', locals: { form: } %>
      <%= form.text_field :expenditure_category_code,
                          value: params[:expenditure_category_code],
                          label: 'Indicator tip de cheltuială',
                          help: 'Exemplu: C1' %>
      <%= form.select :financing_source_ids,
                      FinancingSource.order(:name).map { |financing_source|
                        [financing_source.name, financing_source.id]
                      },
                      {
                        multiple: true,
                        selected: @financing_source_ids,
                        label: 'Sursă de finanțare (centru de cost)',
                        wrapper: { class: 'col-12' }
                      },
                      {
                        data: {
                          use_select2: true,
                          placeholder: 'Selectează o sursă de finanțare...'
                        }
                      } %>
      <%= form.select :project_category_ids,
                      ProjectCategory.order(:name).map { |project_category|
                        [project_category.name, project_category.id]
                      },
                      {
                        multiple: true,
                        selected: @project_category_ids,
                        label: 'Categorie de proiect',
                        wrapper: { class: 'col-12' }
                      },
                      {
                        data: {
                          use_select2: true,
                          placeholder: 'Selectează o categorie de proiect...'
                        }
                      } %>
      <%= form.select :expenditure_article_ids,
                      ExpenditureArticle.order(:code).map { |expenditure_article|
                        ["#{expenditure_article.code} - #{expenditure_article.name}", expenditure_article.id]
                      },
                      {
                        multiple: true,
                        selected: @expenditure_article_ids,
                        label: 'Articol de cheltuială',
                        wrapper: { class: 'col-12' }
                      },
                      {
                        data: {
                          use_select2: true,
                          placeholder: 'Selectează un articol de cheltuială...'
                        }
                      }
      %>
      <%= form.check_box :exclude_cash_receipts,
                         checked: params[:exclude_cash_receipts] == '1' ? true : false,
                         label: 'Exclude încasările' %>
      <%= form.text_field :project_details,
                          value: params[:project_details],
                          label: 'Detalii proiect' %>
      <%= form.text_field :details,
                          value: params[:details],
                          label: 'Detalii cheltuială' %>
      <%= form.text_field :procurement_type,
                          value: params[:procurement_type],
                          label: 'Tip achiziție' %>
      <%= form.text_field :ordinance_number,
                          value: params[:ordinance_number],
                          label: 'Număr ordonanțare' %>
      <%= form.text_field :ordinance_date,
                          value: params[:ordinance_date],
                          label: 'Dată ordonanțare',
                          data: { datepicker: true, max_date: Time.zone.today.strftime('%d.%m.%Y') } %>
      <%= render partial: 'application/filters/value_filter', locals: { form: } %>
      <%= form.select :payment_type_ids,
                      PaymentType.order(:name).map { |payment_type|
                        [payment_type.name, payment_type.id]
                      },
                      {
                        multiple: true,
                        selected: @payment_type_ids,
                        label: 'Tip de plată',
                        wrapper: { class: 'col-3' }
                      },
                      {
                        data: {
                          use_select2: true,
                          placeholder: 'Selectează un tip de plată...'
                        }
                      } %>
      <%= form.text_field :beneficiary,
                          value: params[:beneficiary],
                          label: 'Beneficiar' %>
      <%= form.text_field :invoice,
                          value: params[:invoice],
                          label: 'Factură' %>
      <%= form.text_field :noncompliance,
                          value: params[:noncompliance],
                          label: 'Neconformitate' %>
      <%= form.text_field :remarks,
                          value: params[:remarks],
                          label: 'Observații' %>
      <%= render partial: 'application/filters/user_filter',
                 locals: {
                   form:,
                   id: :created_by_user_ids,
                   label: 'Creat de utilizatorul',
                   selected: @created_by_user_ids
                 }
      %>
      <%= render partial: 'application/filters/user_filter',
                 locals: {
                   form:,
                   id: :updated_by_user_ids,
                   label: 'Modificat de utilizatorul',
                   selected: @updated_by_user_ids
                 }
      %>
      <div class="col-12">
        <%= render partial: 'filter_button', locals: { form: } %>
      </div>
    <% end %>
  </div>
</div>

<turbo-frame id="expenditures-table">
  <%= will_paginate @paginated_expenditures, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

  <div class="top-scrollbar">
    <div class="filler"></div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th scope="col">Acțiuni</th>
        <th scope="col">Număr de înregistrare</th>
        <th scope="col">Data înregistrării</th>
        <th scope="col">Sursă de finanțare</th>
        <th scope="col">Categorie proiect</th>
        <th scope="col">Detalii proiect</th>
        <th scope="col">Articol de cheltuială</th>
        <th scope="col">Valoare plată (RON)</th>
        <th scope="col">Detalii</th>
        <th scope="col">Tip achiziție</th>
        <th scope="col">Număr ordonanțare</th>
        <th scope="col">Dată ordonanțare</th>
        <th scope="col">Tip de plată</th>
        <th scope="col">Beneficiar</th>
        <th scope="col">Factură</th>
        <th scope="col">Neconformitate</th>
        <th scope="col">Observații</th>
        <th scope="col">Creat de</th>
        <th scope="col">Creat la data de</th>
        <th scope="col">Modificat de</th>
        <th scope="col">Modificat la data de</th>
      </tr>
      </thead>
      <tbody>
      <% @paginated_expenditures.each do |expenditure| %>
        <tr>
          <td class="d-grid gap-1">
            <%= link_to 'Duplică',
                        duplicate_expenditure_path(expenditure.id),
                        target: '_top',
                        class: 'btn btn-info' %>
            <%= link_to new_commitment_path(source_expenditure_id: expenditure.id),
                        target: '_top',
                        class: 'btn btn-primary' do %>
              Convertește <span class="text-nowrap">în angajament</span>
            <% end %>
            <% if can_modify_expenditures %>
              <%= link_to 'Editează',
                          edit_expenditure_path(expenditure.id),
                          target: '_top',
                          class: 'ms-1 btn btn-warning' %>
            <% end %>
          </td>
          <th
            scope="row"
            style="background-color: <%= expenditure.created_by_user.background_color %>; color: <%= expenditure.created_by_user.text_color %>"
          ><%= expenditure.registration_number %>/<%= expenditure.year %></th>
          <td><%= expenditure.registration_date.strftime('%d.%m.%Y') %></td>
          <td><%= expenditure.financing_source&.name %></td>
          <td><%= expenditure.project_category&.name %></td>
          <td><%= expenditure.project_details %></td>
          <td><%= "#{expenditure.expenditure_article&.code} - #{expenditure.expenditure_article&.name}" %></td>
          <td><%= number_to_currency expenditure.value, unit: '' %></td>
          <td><%= expenditure.details %></td>
          <td><%= expenditure.procurement_type %></td>
          <td><%= expenditure.ordinance_number %></td>
          <td><%= expenditure.ordinance_date&.strftime('%d.%m.%Y') %></td>
          <td><%= expenditure.payment_type&.name %></td>
          <td><%= expenditure.beneficiary %></td>
          <td><%= expenditure.invoice %></td>
          <td><%= expenditure.noncompliance %></td>
          <td><%= expenditure.remarks %></td>
          <td><%= expenditure.created_by_user.full_name %></td>
          <td><%= expenditure.created_at.strftime('%d.%m.%Y la %H:%M ora României') %></td>
          <td><%= expenditure.updated_by_user.full_name %></td>
          <td><%= expenditure.updated_at.strftime('%d.%m.%Y la %H:%M ora României') %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
      <% if @expenditures.empty? %>
        <tr>
          <td colspan="17" class="ps-5 py-3">
            <% if @any_filters_applied %>
              Nu a fost găsită nicio cheltuială care să se potrivească cu criteriile introduse.
            <% else %>
              Nu a fost adăugată încă nicio cheltuială.
            <% end %>
          </td>
        </tr>
      <% end %>
      </tfoot>
    </table>
  </div>

  <%= will_paginate @paginated_expenditures, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</turbo-frame>